RegisterNetEvent('simpleHeal:healPlayer')
AddEventHandler('simpleHeal:healPlayer', function()
    local ped = PlayerPedId()
    SetEntityHealth(ped, Config.MaxHealth)
    ClearPedBloodDamage(ped)
end)
